#
# Copyright (C) 2019 Assured Information Security, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |

    sudo apt-get install git build-essential clang #cmake

    CMAKE_URL="http://www.cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.tar.gz"
    mkdir custom_cmake
    wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C custom_cmake
    export PATH=$(pwd)/custom_cmake/bin:${PATH}

    mkdir working
    mkdir working/build
    mkdir working/prefix
    mkdir working/cache

    git clone https://github.com/Bareflank/standalone_cxx.git working/standalone_cxx
    cd working/build

    cmake ../standalone_cxx
    make -j2

    make quick
  displayName: 'Run integration tests'
